title: Neural Network-based Magnetometer Sensor Model for Virtual Magnetic-based Navigation Testbed
description: Aditya Penumarti, Nikhil Iyer, Loi Park, Kristy Waters, Humberto Ramos, Jane Shin 
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  repo_url: https://github.com/aprilab-uf/nn_magnetometer.git
  sim_url: https://github.com/aprilab-uf/magnav_isaac_sim.git
  pdf_url: assets/pdf/NNMagnetometer_AIAA_SciTech_2025.pdf
