title: Neural Network-based Magnetometer Sensor Model for Virtual Magnetic-based Navigation Testbed
description: Aditya Penumarti, Nikhil Iyer, Humberto Ramos, Jane Shin 
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  zip_url: https://github.com/aditya-penumarti/magnav-nn-sim-isaac
