title: Neural Network-based Magnetometer Sensor Model for Virtual Magnetic-based Navigation Testbed
description: This page houses the downloads the the neural-based simulation for the virtual testbed for MagNav.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
